server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.250.172.176:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: coffeeshop
          contentType: application/json
        event-out:
          destination: coffeeshop
          contentType: application/json
feign:
  payment:
    url: localhost:8083
  hystrix:
    enabled: true

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082

#feign:
#  hystrix:
#    enabled: true

# To set thread isolation to SEMAPHORE
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

#hystrix:
#  command:
#    # 전역설정
#    default:
#      execution.isolation.thread.timeoutInMilliseconds: 610

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: coffeeshop
          contentType: application/json
        event-out:
          destination: coffeeshop
          contentType: application/json

feign:
  payment:
    url: payment:8080